/**
 * Cartographie de l EN 1992-1-1:2023 (CDC v4 §5.2), forme exploitable.
 *
 * Forme lisible, decisions de perimetre et reserves : docs/cartographie/en1992.md.
 * Granularite : la sous-clause a trois chiffres lorsqu elle existe, sinon la
 * clause a deux chiffres. Les chapitres 0 a 3 (introduction, domaine,
 * references, symboles) ne portent aucune regle de calcul et ne sont pas
 * cartographies.
 *
 * `verifie` reste a `null` tant que l auteur n a pas lui-meme controle
 * l article et ses chiffres : aucun outil ne renseigne ce champ.
 */

import type { Generation } from '../../src/noyau/model/resultat';
import type { Carte } from './types';
import { ann, c, exclu, n, reporte } from './outils';

const G1: Generation = 'ec2-2004';
const G2: Generation = 'ec2-2023';

export const EN1992: Carte = {
  id: 'en1992',
  norme: 'EN 1992-1-1:2023',
  correspondant: 'EN 1992-1-1:2004 + A1:2014',
  chapitres: [
    {
      numero: '4',
      titre: 'Bases de calcul',
      clauses: [
        c('4.1', 'Règles générales : exigences, fiabilité, durée d’utilisation', ['2.1']),
        c('4.2', 'Variables de base : actions dépendant du temps, géométrie', ['2.3']),
        c('4.3', 'Coefficients partiels : retrait, précontrainte, matériaux', ['2.4'], { annexes: [ann('A', 'informative')] }),
        c('4.4', 'Connexion d’éléments aux éléments en béton', []),
      ],
    },
    {
      numero: '5',
      titre: 'Matériaux',
      clauses: [
        c('5.1.1', 'Béton : généralités', ['3.1.1']),
        c('5.1.2', 'Béton : propriétés et conditions associées', ['3.1.1', '3.1.2'], { annexes: [ann('C', 'normative')] }),
        c('5.1.3', 'Béton : résistance', ['3.1.2']),
        c('5.1.4', 'Béton : déformation élastique', ['3.1.3']),
        c('5.1.5', 'Béton : fluage et retrait', ['3.1.4'], { annexes: [ann('B', 'normative')] }),
        c('5.1.6', 'Béton : hypothèses de calcul, résistance de calcul', ['3.1.6'], {
          article: 'materiaux',
          ingeree: true,
          niveaux: [n(G1, 'materiaux', 'base', '3.1.6'), n(G2, 'materiaux', 'base', '5.1.6')],
        }),
        c('5.2.1', 'Aciers pour béton armé : généralités', ['3.2.1']),
        c('5.2.2', 'Aciers pour béton armé : propriétés et classes de ductilité', ['3.2.2', '3.2.4'], { annexes: [ann('C', 'normative')] }),
        c('5.2.3', 'Soudage des armatures', ['3.2.5']),
        c('5.2.4', 'Aciers pour béton armé : hypothèses de calcul', ['3.2.7']),
        c('5.2.5', 'Coupleurs d’armatures', []),
        c('5.2.6', 'Armatures à tête d’ancrage', []),
        c('5.3', 'Armatures de précontrainte', ['3.3']),
        c('5.4', 'Systèmes de précontrainte, zones d’ancrage', ['3.4']),
      ],
    },
    {
      numero: '6',
      titre: 'Durabilité et enrobage',
      clauses: [
        c('6.1', 'Durabilité : généralités', ['4.1']),
        c('6.2', 'Exigences de durabilité', ['4.3']),
        c('6.3', 'Conditions d’environnement et classes d’exposition', ['4.2']),
        c('6.4', 'Classes de résistance à l’exposition', [], exclu('classes de résistance à l’exposition hors version 1 (CDC §1)')),
        c('6.5.1', 'Enrobage nominal', ['4.4.1.1'], { article: 'durabilite-enrobage', ingeree: true }),
        c('6.5.2', 'Enrobage minimal', ['4.4.1.2'], {
          article: 'durabilite-enrobage',
          ingeree: true,
          annexes: [ann('P', 'informative')],
          niveaux: [n(G1, 'enrobage', 'base', '4.4.1'), n(G2, 'enrobage', 'base', '6.5'), n(G2, 'enrobage', 'annexe-p', 'P', 'annexe-informative')],
        }),
        c('6.5.3', 'Tolérances d’exécution de l’enrobage', ['4.4.1.3'], { article: 'durabilite-enrobage', ingeree: true }),
      ],
    },
    {
      numero: '7',
      titre: 'Analyse structurale',
      clauses: [
        c('7.1', 'Analyse : généralités', ['5.1']),
        c('7.2.1', 'Imperfections géométriques', ['5.2'], {
          article: 'imperfections',
          ingeree: true,
          niveaux: [
            n(G1, 'imperfections', 'inclinaison', '5.2(5)'),
            n(G1, 'imperfections', 'excentricite', '5.2(7)'),
            n(G1, 'imperfections', 'simplifie', '5.2(9)'),
            n(G2, 'imperfections', 'inclinaison', '7.2.1.2(2)'),
            n(G2, 'imperfections', 'excentricite', '7.2.1.2(5)'),
            n(G2, 'imperfections', 'simplifie', '7.2.1.2(5)'),
            n(G2, 'imperfections', 'mode', '7.2.1.2(4)'),
          ],
          reserves: 'Majoration de 1,2 pour des tolérances plus strictes (7.2.1.1(3)) non codée.',
        }),
        c('7.2.2', 'Modélisation de la structure', ['5.3.1']),
        c('7.2.3', 'Données géométriques : largeur participante, portée de calcul', ['5.3.2']),
        c('7.3.1', 'Analyse élastique-linéaire', ['5.4']),
        c('7.3.2', 'Analyse élastique-linéaire avec redistribution des moments', ['5.5'], {
          article: 'redistribution',
          ingeree: true,
          niveaux: [
            n(G1, 'redistribution', 'base', '5.5(4)'),
            n(G2, 'redistribution', 'base', '7.3.2(3)'),
            n(G2, 'redistribution', 'rotation', '7.3.2(5)'),
          ],
          reserves: 'Vérification explicite de la capacité de rotation (7.18 à 7.24) et précontrainte (7.17) non codées.',
        }),
        c('7.3.3', 'Analyse plastique', ['5.6']),
        c('7.3.4', 'Analyse non linéaire', ['5.7'], { ...exclu('analyse non linéaire hors version 1 (CDC §1)'), annexes: [ann('F', 'informative')] }),
        c('7.4.1', 'Second ordre : généralités', ['5.8.1', '5.8.2', '5.8.3'], {
          article: 'second-ordre',
          ingeree: true,
          annexes: [ann('O', 'informative')],
          niveaux: [n(G1, 'elancement-limite', 'base', '5.8.3.1'), n(G2, 'elancement-limite', 'base', 'O.6', 'annexe-informative')],
          reserves: 'Critère global F_V,B / F_V,Ed ≥ 10 (7.25) et charge de flambement des structures (O.1 à O.6) non codés.',
        }),
        c('7.4.2', 'Second ordre : fluage', ['5.8.4']),
        c('7.4.3', 'Second ordre : méthodes d’analyse', ['5.8.5', '5.8.6', '5.8.7', '5.8.8'], {
          article: 'second-ordre',
          ingeree: true,
          annexes: [ann('O', 'informative')],
          niveaux: [
            n(G1, 'courbure-nominale', 'courbure', '5.8.8'),
            n(G2, 'courbure-nominale', 'kr-1', 'O.7.3(3)', 'annexe-informative'),
            n(G2, 'courbure-nominale', 'kr-precis', 'O.7.3(3)', 'annexe-informative'),
            n(G1, 'rigidite-nominale', 'base', '5.8.7.2(2)'),
            n(G1, 'rigidite-nominale', 'simplifiee', '5.8.7.2(3)'),
            n(G2, 'rigidite-nominale', 'base', 'O.8', 'annexe-informative'),
          ],
          reserves: 'Troisième terme de l’enveloppe (O.13) à relire sur l’exemplaire ; rigidité de plastification (7.4.3.2) remplacée par la valeur forfaitaire 0,4 E_cd I_c de O.8.1(5) ; majoration des forces horizontales (O.24) non codée.',
        }),
        c('7.4.4', 'Compression avec flexion déviée', ['5.8.9']),
        c('7.5', 'Déversement des poutres élancées', ['5.9']),
        c('7.6.1', 'Précontrainte : généralités', ['5.10.1']),
        c('7.6.2', 'Force de précontrainte', ['5.10.2', '5.10.3']),
        c('7.6.3', 'Pertes instantanées', ['5.10.4', '5.10.5']),
        c('7.6.4', 'Pertes différées', ['5.10.6']),
        c('7.6.5', 'Effets de la précontrainte à l’ELU', ['5.10.8']),
      ],
    },
    {
      numero: '8',
      titre: 'État-limite ultime',
      clauses: [
        c('8.1.1', 'Flexion et flexion composée : généralités', ['6.1']),
        c('8.1.2', 'Diagramme de calcul du béton comprimé', ['3.1.7'], {
          article: 'flexion',
          ingeree: true,
          niveaux: [n(G1, 'flexion', 'rectangle', '3.1.7(3)'), n(G1, 'flexion', 'parabole', '3.1.7(1)'), n(G2, 'flexion', 'parabole', '8.1.2(1)')],
          reserves: 'Bloc rectangulaire de la figure 8.2 d) non codé (paramètres sur figure seulement).',
        }),
        c('8.1.3', 'Flexion des dalles', [], { annexes: [ann('G', 'normative')] }),
        c('8.1.4', 'Béton confiné', ['3.1.9'], exclu('confinement hors version 1 (CDC §1)')),
        c('8.2.1', 'Effort tranchant : procédure générale', ['6.2.1'], {
          article: 'tranchant-sans-armature',
          ingeree: true,
          niveaux: [
            n(G2, 'tranchant-sans-armature', 'tau-min', '8.2.1(4)'),
            n(G1, 'tranchant-dalle-bidirectionnelle', 'sans-equivalent', '6.2.2'),
            n(G2, 'tranchant-dalle-bidirectionnelle', 'paliers', '8.2.1(5)'),
            n(G2, 'tranchant-dalle-bidirectionnelle', 'angle', '(8.25)'),
          ],
        }),
        c('8.2.2', 'Éléments sans armature d’effort tranchant', ['6.2.2'], {
          article: 'tranchant-sans-armature',
          ingeree: true,
          annexes: [ann('I.8.3.1', 'informative')],
          niveaux: [
            n(G1, 'tranchant-sans-armature', 'base', '6.2.2(1)'),
            n(G1, 'tranchant-sans-armature', 'effort-normal', '6.2.2(1)'),
            n(G2, 'tranchant-sans-armature', 'hauteur-utile', '8.2.2(1)'),
            n(G2, 'tranchant-sans-armature', 'portee-mecanique', '8.2.2(3)'),
            n(G2, 'tranchant-sans-armature', 'kvp', '8.2.2(4)'),
            n(G2, 'tranchant-sans-armature', 'kvp-portee', '8.2.2(4)'),
            n(G2, 'tranchant-sans-armature', 'compression', '8.2.2(5)'),
            n(G2, 'tranchant-sans-armature', 'annexe-i', 'I.8.3.1', 'annexe-informative'),
            n(G2, 'tranchant-sans-armature', 'annexe-i-kvd', 'I.8.3.1(3)', 'annexe-informative'),
          ],
          reserves:
            'Précontrainte (8.36), (8.37), réduction ΔV_Ed des charges réparties 8.2.2(8) et charges près des appuis 8.2.2(9) non codées ; lecture de d/(3 a_cs) dans (8.31) et application de k_vd avec plancher τ_Rdc,min, à confirmer.',
        }),
        c('8.2.3', 'Éléments avec armatures d’effort tranchant', ['6.2.3'], {
          article: 'tranchant-avec-armature',
          ingeree: true,
          niveaux: [
            n(G1, 'tranchant-avec-armature', 'base', '6.2.3'),
            n(G2, 'tranchant-avec-armature', 'nu-constant', '8.2.3'),
            n(G2, 'tranchant-avec-armature', 'nu-variable', '8.2.3'),
          ],
        }),
        c('8.2.4', 'Effort tranchant dans le plan et flexion transversale', ['6.2.1(8)', '6.2.3(8)'], { annexes: [ann('G', 'normative')] }),
        c('8.2.5', 'Cisaillement entre l’âme et la table', ['6.2.4'], {
          article: 'ame-table',
          ingeree: true,
          niveaux: [
            n(G1, 'ame-table', 'seuil', '6.2.4(6)'),
            n(G1, 'ame-table', 'treillis', '6.2.4(4)'),
            n(G2, 'ame-table', 'seuil', '8.2.5(2)'),
            n(G2, 'ame-table', 'treillis', '8.2.5(4)'),
          ],
        }),
        c('8.2.6', 'Cisaillement aux interfaces', ['6.2.5'], {
          article: 'cisaillement-interfaces',
          ingeree: true,
          niveaux: [
            n(G1, 'interface', 'base', '6.2.5'),
            n(G2, 'interface', 'armatures-ancrees', '8.2.6(5)'),
            n(G2, 'interface', 'ancrage-insuffisant', '8.2.6(7)'),
          ],
        }),
        c('8.3.1', 'Torsion : considérations générales', ['6.3.1']),
        c('8.3.2', 'Torsion : efforts internes, sections pleines ou fermées', ['6.3.2(1)']),
        c('8.3.3', 'Torsion : sections ouvertes', ['6.3.1(4)']),
        c('8.3.4', 'Résistance en torsion des sections pleines ou fermées', ['6.3.2'], {
          article: 'torsion',
          ingeree: true,
          niveaux: [n(G1, 'torsion', 'base', '6.3.2'), n(G2, 'torsion', 'cot-1', '8.3.4(3)'), n(G2, 'torsion', 'cot-variable', '8.3.4(4)')],
        }),
        c('8.3.5', 'Actions combinées : procédure', ['6.3.2(4)']),
        c('8.3.6', 'Formule d’interaction', ['6.3.2(4)']),
        c('8.4.1', 'Poinçonnement : généralités et procédure', ['6.4.1', '6.4.3'], {
          article: 'poinconnement',
          ingeree: true,
          niveaux: [n(G2, 'poinconnement', 'tau-min', '8.4.1(2)')],
        }),
        c('8.4.2', 'Poinçonnement : hauteur utile, contour de contrôle, contrainte', ['6.4.2', '6.4.3'], { article: 'poinconnement', ingeree: true }),
        c('8.4.3', 'Poinçonnement des dalles sans armatures', ['6.4.4'], {
          article: 'poinconnement',
          ingeree: true,
          niveaux: [
            n(G1, 'poinconnement', 'base', '6.4.4'),
            n(G2, 'poinconnement', 'hauteur-utile', '8.4.3(1)'),
            n(G2, 'poinconnement', 'moment-nul', '8.4.3(2)'),
          ],
        }),
        c('8.4.4', 'Poinçonnement des dalles avec armatures', ['6.4.5'], {
          article: 'poinconnement-arme',
          ingeree: true,
          niveaux: [n(G1, 'poinconnement-arme', 'base', '6.4.5'), n(G2, 'poinconnement-arme', 'base', '8.4.4')],
        }),
        c('8.5.1', 'Bielles-tirants et champs de contrainte : généralités', ['6.5.1']),
        c('8.5.2', 'Bielles et champs de compression', ['6.5.2'], {
          article: 'bielles-tirants',
          ingeree: true,
          niveaux: [
            n(G1, 'bielles', 'base', '6.5.2'),
            n(G2, 'bielles', 'paliers', '8.5.2(4)'),
            n(G2, 'bielles', 'continu', '(8.119)'),
            n(G2, 'bielles', 'deformation', '8.5.2(5)'),
          ],
          reserves: 'Confinement (8.5.2(6)), armatures comprimées (8.5.2(7)) et gaines (8.5.2(8)) non codés.',
        }),
        c('8.5.3', 'Tirants', ['6.5.3']),
        c('8.5.4', 'Nœuds', ['6.5.4'], {
          article: 'bielles-tirants',
          ingeree: true,
          reserves: 'Interpolation de ν pour un ancrage en partie dans le nœud (8.5.4.3(4)) non codée ; majorations de 2004 (6.5.4(5), (6)) non codées.',
        }),
        c('8.5.5', 'Diffusion de forces concentrées', ['6.5.3(3)'], {
          article: 'bielles-tirants',
          ingeree: true,
          niveaux: [n(G1, 'diffusion', 'base', '6.5.3(3)'), n(G2, 'diffusion', 'base', '8.5.5')],
          reserves: 'Lecture de la formule (8.124), tan θ_cf = (1 − a/b)/2, à confirmer sur l’exemplaire.',
        }),
        c('8.6', 'Pressions localisées', ['6.7'], {
          article: 'pressions-localisees',
          ingeree: true,
          niveaux: [n(G1, 'pression-localisee', 'base', '6.7'), n(G2, 'pression-localisee', 'base', '8.6')],
        }),
      ],
    },
    {
      numero: '9',
      titre: 'États-limites de service',
      clauses: [
        c('9.1', 'ELS : généralités', ['7.1']),
        c('9.2.1', 'Contraintes et fissuration : considérations générales', ['7.2', '7.3.1'], {
          article: 'contraintes-service',
          ingeree: true,
          annexes: [ann('D', 'informative')],
          niveaux: [
            n(G1, 'contraintes-els', 'acier', '7.2(5)'),
            n(G1, 'contraintes-els', 'beton-caracteristique', '7.2(2)'),
            n(G1, 'contraintes-els', 'beton-quasi-permanent', '7.2(3)'),
            n(G2, 'contraintes-els', 'acier', '9.2.1'),
            n(G2, 'contraintes-els', 'beton-caracteristique', '9.2.1'),
            n(G2, 'contraintes-els', 'beton-quasi-permanent', '9.1(4)'),
          ],
          reserves: 'Annexe D (fissuration due aux déformations gênées) non traitée ; précontrainte (σ_p ≤ 0,8 f_pk) non codée.',
        }),
        c('9.2.2', 'Armatures minimales de maîtrise de la fissuration', ['7.3.2'], {
          article: 'armatures-minimales',
          ingeree: true,
          annexes: [ann('S', 'informative')],
          niveaux: [n(G1, 'fissuration-minimale', 'base', '7.3.2'), n(G2, 'fissuration-minimale', 'base', '9.2.2')],
          reserves: 'Annexe S (armatures minimales et fissuration simplifiée) non traitée.',
        }),
        c('9.2.3', 'Maîtrise de la fissuration par le calcul', ['7.3.3', '7.3.4'], {
          article: 'fissuration',
          ingeree: true,
          annexes: [ann('S', 'informative')],
          niveaux: [
            n(G1, 'fissuration', 'base', '7.3.4'),
            n(G2, 'fissuration', 'base', '9.2.3'),
            n(G2, 'fissuration', 'annexe-s', 'S', 'annexe-informative'),
          ],
          reserves: 'Critère « barres isolées » de la figure 9.3 b) à confirmer ; annexe S non traitée.',
        }),
        c('9.3.1', 'Flèches : considérations générales', ['7.4.1']),
        c('9.3.2', 'Flèches par le rapport portée / hauteur utile', ['7.4.2'], {
          article: 'elancement',
          ingeree: true,
          niveaux: [n(G1, 'elancement', 'base', '7.4.2'), n(G2, 'elancement', 'base', '9.3.2')],
        }),
        c('9.3.3', 'Calcul simplifié des flèches', ['7.4.3'], {
          article: 'fleche',
          ingeree: true,
          niveaux: [n(G2, 'fleche', 'simplifiee', '9.3.3')],
        }),
        c('9.3.4', 'Méthode générale de calcul des flèches', ['7.4.3'], {
          article: 'fleche',
          ingeree: true,
          niveaux: [n(G1, 'fleche', 'generale', '7.4.3'), n(G2, 'fleche', 'generale', '9.3.4')],
        }),
        c('9.4', 'Vibrations', []),
      ],
    },
    {
      numero: '10',
      titre: 'Fatigue',
      clauses: [
        c('10.1', 'Fatigue : généralités', ['6.8.1'], { annexes: [ann('E', 'normative')] }),
        c('10.2', 'Combinaison d’actions', ['6.8.3']),
        c('10.3', 'Efforts et contraintes pour la fatigue', ['6.8.2']),
        c('10.4', 'Armatures : vérification simplifiée', ['6.8.4', '6.8.5', '6.8.6']),
        c('10.5', 'Béton comprimé : vérification simplifiée', ['6.8.7']),
        c('10.6', 'Béton cisaillé : vérification simplifiée', ['6.8.7(4)']),
        c('10.7', 'Surfaces de reprise : vérification simplifiée', []),
      ],
    },
    {
      numero: '11',
      titre: 'Dispositions constructives des armatures',
      clauses: [
        c('11.1', 'Dispositions : généralités', ['8.1']),
        c('11.2', 'Espacement des armatures', ['8.2'], {
          article: 'espacement-paquets',
          ingeree: true,
          niveaux: [n(G1, 'espacement', 'base', '8.2'), n(G2, 'espacement', 'base', '11.2')],
          reserves: 'Distance à une surface déjà bétonnée (11.2(4)) et armatures scellées (11.2(5)) non codées.',
        }),
        c('11.3', 'Diamètres des mandrins', ['8.3']),
        c('11.4.1', 'Ancrage : généralités', ['8.4.1']),
        c('11.4.2', 'Ancrage des barres droites', ['8.4.2', '8.4.3', '8.4.4'], {
          article: 'ancrage',
          ingeree: true,
          niveaux: [
            n(G1, 'ancrage', 'barre-plastifiee', '8.4.3'),
            n(G1, 'ancrage', 'contrainte-reelle', '8.4.3'),
            n(G2, 'ancrage', 'barre-plastifiee', '11.4.2'),
            n(G2, 'ancrage', 'contrainte-reelle', '11.4.2'),
          ],
        }),
        c('11.4.3', 'Ancrage des paquets de barres', ['8.9.2'], {
          article: 'espacement-paquets',
          ingeree: true,
          reserves: 'Diamètre équivalent calculé ; la longueur d’ancrage se calcule avec le calculateur d’ancrage en y saisissant φb.',
        }),
        c('11.4.4', 'Ancrage par coude ou crochet', ['8.4.4'], {
          article: 'ancrage-crochet',
          ingeree: true,
          niveaux: [
            n(G1, 'ancrage-crochet', 'barre-plastifiee', '8.4.4'),
            n(G1, 'ancrage-crochet', 'contrainte-reelle', '8.4.4'),
            n(G2, 'ancrage-crochet', 'barre-plastifiee', '11.4.4'),
            n(G2, 'ancrage-crochet', 'contrainte-reelle', '11.4.4'),
          ],
        }),
        c('11.4.5', 'Ancrage par barres transversales soudées', ['8.4.4', '8.6'], {
          article: 'ancrage-soude-boucle',
          ingeree: true,
          niveaux: [
            n(G1, 'ancrage-soude', 'barre-plastifiee', '8.4.4'),
            n(G1, 'ancrage-soude', 'contrainte-reelle', '8.4.4'),
            n(G2, 'ancrage-soude', 'barre-plastifiee', '11.4.5'),
            n(G2, 'ancrage-soude', 'contrainte-reelle', '11.4.5'),
          ],
          reserves: 'Capacité des barres soudées de 2004 (8.6, formules (8.8) et (8.9)) et appuis directs (note du tableau 8.2) non codés.',
        }),
        c('11.4.6', 'Ancrage par boucles en U', ['8.4.4'], {
          article: 'ancrage-soude-boucle',
          ingeree: true,
          niveaux: [
            n(G1, 'ancrage-boucle', 'barre-plastifiee', '8.4.4'),
            n(G1, 'ancrage-boucle', 'contrainte-reelle', '8.4.4'),
            n(G2, 'ancrage-boucle', 'barre-plastifiee', '11.4.6'),
            n(G2, 'ancrage-boucle', 'contrainte-reelle', '11.4.6'),
          ],
          reserves: 'Ancrage sans longueur d’une boucle en traction pure (11.4.6(1)) non codé.',
        }),
        c('11.4.7', 'Ancrage par tête d’ancrage', [], {
          article: 'tete-ancrage',
          ingeree: true,
          niveaux: [n(G2, 'tete-ancrage', 'simplifie', '11.4.7(1)')],
          reserves: 'Vérification générale (11.8) à (11.11) non codée : lecture des formules à confirmer.',
        }),
        c('11.4.8', 'Ancrage des armatures scellées', []),
        c('11.5.1', 'Recouvrements : généralités', ['8.7.1', '8.7.2']),
        c('11.5.2', 'Recouvrements : tous types', ['8.7.3', '8.7.4'], { article: 'ancrage', ingeree: true }),
        c('11.5.3', 'Recouvrement de paquets', ['8.9.3'], {
          article: 'espacement-paquets',
          ingeree: true,
          reserves: 'Règles de décalage décrites dans l’article, non codées.',
        }),
        c('11.5.4', 'Recouvrement par boucles en U', []),
        c('11.5.5', 'Recouvrement par barres à tête', []),
        c('11.5.6', 'Coupleurs mécaniques', []),
        c('11.5.7', 'Jonctions soudées', []),
        c('11.6', 'Armatures de précontrainte par post-tension', ['8.10']),
        c('11.7', 'Efforts de déviation des membrures courbes', []),
      ],
    },
    {
      numero: '12',
      titre: 'Dispositions des éléments et règles particulières',
      clauses: [
        c('12.1', 'Éléments : généralités', ['9.1']),
        c('12.2', 'Armatures minimales de non-fragilité', ['9.2.1.1'], {
          article: 'armatures-minimales',
          ingeree: true,
          niveaux: [
            n(G1, 'non-fragilite', 'base', '9.2.1.1'),
            n(G2, 'non-fragilite', 'z-forfaitaire', '12.2(2)'),
            n(G2, 'non-fragilite', 'z-equilibre', '12.2(2)'),
            n(G2, 'non-fragilite', 'kdc', '12.2(3)'),
            n(G1, 'armature-tranchant-minimale', 'base', '9.2.2(5)'),
            n(G2, 'armature-tranchant-minimale', 'base', '12.2(4)'),
            n(G2, 'armature-tranchant-minimale', 'ductilite', '12.2(4)'),
          ],
        }),
        c('12.3.1', 'Poutres : généralités', ['9.2']),
        c('12.3.2', 'Poutres : armatures longitudinales', ['9.2.1']),
        c('12.3.3', 'Poutres : armatures d’effort tranchant et de torsion', ['9.2.2', '9.2.3']),
        c('12.3.4', 'Poutres : armatures de suspension aux appuis indirects', ['9.2.5']),
        c('12.4.1', 'Dalles : généralités', ['9.3.1']),
        c('12.4.2', 'Dalles : armatures d’effort tranchant', ['9.3.2']),
        c('12.5.1', 'Armatures de poinçonnement', ['9.4.3']),
        c('12.5.2', 'Armatures d’intégrité des planchers-dalles', []),
        c('12.6', 'Poteaux', ['9.5']),
        c('12.7', 'Voiles et poutres-cloisons', ['9.6', '9.7']),
        c('12.8', 'Fondations', ['9.8']),
        c('12.9', 'Chaînages', ['9.10'], {
          article: 'chainages',
          ingeree: true,
          niveaux: [n(G1, 'chainages', 'base', '9.10.2'), n(G2, 'chainages', 'ossature', 'EN 1991-1-7 A.3.1', 'annexe-informative')],
          reserves: 'Murs porteurs (EN 1991-1-7 A.3.2, formules (A.3), (A.4)), chaînages verticaux et lignes de poutres de 2004 (9.10.2.3(4)) non codés.',
        }),
        c('12.10', 'Appuis et joints de dilatation', []),
      ],
    },
    {
      numero: '13',
      titre: 'Éléments et structures préfabriqués',
      clauses: [
        c('13.1', 'Préfabrication : généralités', ['10.1']),
        c('13.2', 'Exigences spécifiques', ['10.2']),
        c('13.3', 'Béton : cure thermique, fluage et retrait', ['10.3']),
        c('13.4', 'Analyse structurale', ['10.5']),
        c('13.5', 'Armatures de précontrainte pré-tendues', ['8.10.2', '10.5.2']),
        c('13.6', 'Systèmes de plancher', ['10.9.3']),
        c('13.7', 'Assemblages et appuis', ['10.9.4', '10.9.5']),
        c('13.8', 'Fondations en encuvement', ['10.9.6']),
      ],
    },
    {
      numero: '14',
      titre: 'Béton non armé ou faiblement armé',
      clauses: [
        c('14.1', 'Béton non armé : généralités', ['12.1']),
        c('14.2', 'Béton', ['12.3']),
        c('14.3', 'Analyse structurale', ['12.5']),
        c('14.4', 'ELU : flexion composée, effort tranchant, torsion', ['12.6']),
        c('14.5', 'ELS', ['12.7']),
        c('14.6', 'Dispositions des éléments', ['12.9']),
      ],
    },
    {
      numero: 'Annexes',
      titre: 'Annexes non rattachées à une clause',
      clauses: [
        c('K', 'Ponts (normative)', ['EN 1992-2']),
        c('M', 'Béton de granulats légers (normative)', ['11'], reporte('granulats légers : en attente, décision de l’auteur (05/10/2026)')),
        c('H', 'Étanchéité des structures (informative)', ['EN 1992-3'], exclu('retenue de liquides hors version 1 (CDC §1)')),
        c('I', 'Évaluation des structures existantes (informative), hors I.8.3.1', [], exclu('structures existantes hors version 1 (CDC §1)')),
        c('J', 'Renforcement par PRFC (informative)', [], exclu('renforcement par CFRP hors version 1 (CDC §1)')),
        c('L', 'Béton de fibres métalliques (informative)', [], exclu('béton fibré hors version 1 (CDC §1)')),
        c('N', 'Béton de granulats recyclés (informative)', [], exclu('granulats recyclés hors version 1 (CDC §1)')),
        c('Q', 'Acier inoxydable (normative)', [], exclu('armatures inox hors version 1 (CDC §1)')),
        c('R', 'Armatures en PRF (informative)', [], exclu('armatures composites hors version 1 (CDC §1)')),
      ],
    },
  ],
};
